name: Build and Push OCI Container

env:
  CONTAINER_PLATFORMS: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7
  CONTAINER_REGISTRY: ghcr.io
on:
  push:
    branches: ['**']
    tags: ['v*', 'v*.*', 'v*.*.*']
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/metadata-action@v5
      id: meta
      with:
        images: ${{env.CONTAINER_REGISTRY}}/${{ github.repository }}
        tags: |
          type=ref,event=branch
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
      with:
        platforms: ${{ env.CONTAINER_PLATFORMS }}
    - name: Login to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.CONTAINER_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push container image
      uses: docker/build-push-action@v5
      with:
        push: true
        platforms: ${{ env.CONTAINER_PLATFORMS }}
        tags: ${{ steps.meta.output.tags }}
